package com.shsxt.crm.sales.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class CusDevPlan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.sale_chance_id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private Integer saleChanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.plan_item
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private String planItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.plan_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date planDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.exe_affect
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private String exeAffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.create_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.update_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus_dev_plan.is_valid
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cus_dev_plan
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.id
     *
     * @return the value of t_cus_dev_plan.id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.id
     *
     * @param id the value for t_cus_dev_plan.id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.sale_chance_id
     *
     * @return the value of t_cus_dev_plan.sale_chance_id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Integer getSaleChanceId() {
        return saleChanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.sale_chance_id
     *
     * @param saleChanceId the value for t_cus_dev_plan.sale_chance_id
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setSaleChanceId(Integer saleChanceId) {
        this.saleChanceId = saleChanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.plan_item
     *
     * @return the value of t_cus_dev_plan.plan_item
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public String getPlanItem() {
        return planItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.plan_item
     *
     * @param planItem the value for t_cus_dev_plan.plan_item
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setPlanItem(String planItem) {
        this.planItem = planItem == null ? null : planItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.plan_date
     *
     * @return the value of t_cus_dev_plan.plan_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Date getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.plan_date
     *
     * @param planDate the value for t_cus_dev_plan.plan_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.exe_affect
     *
     * @return the value of t_cus_dev_plan.exe_affect
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public String getExeAffect() {
        return exeAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.exe_affect
     *
     * @param exeAffect the value for t_cus_dev_plan.exe_affect
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setExeAffect(String exeAffect) {
        this.exeAffect = exeAffect == null ? null : exeAffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.create_date
     *
     * @return the value of t_cus_dev_plan.create_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.create_date
     *
     * @param createDate the value for t_cus_dev_plan.create_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.update_date
     *
     * @return the value of t_cus_dev_plan.update_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.update_date
     *
     * @param updateDate the value for t_cus_dev_plan.update_date
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.is_valid
     *
     * @return the value of t_cus_dev_plan.is_valid
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.is_valid
     *
     * @param isValid the value for t_cus_dev_plan.is_valid
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus_dev_plan
     *
     * @mbg.generated Wed Aug 28 13:57:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", saleChanceId=").append(saleChanceId);
        sb.append(", planItem=").append(planItem);
        sb.append(", planDate=").append(planDate);
        sb.append(", exeAffect=").append(exeAffect);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", isValid=").append(isValid);
        sb.append("]");
        return sb.toString();
    }
}