package com.shsxt.crm.sales.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class SaleChance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.id
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.chance_source
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String chanceSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.customer_name
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.cgjl
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private Integer cgjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.overview
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String overview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.link_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String linkMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.link_phone
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String linkPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.description
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.create_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String createMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.assign_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private String assignMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.assign_time
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date assignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.state
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.dev_result
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private Integer devResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.is_valid
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.create_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_chance.update_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sale_chance
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.id
     *
     * @return the value of t_sale_chance.id
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.id
     *
     * @param id the value for t_sale_chance.id
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.chance_source
     *
     * @return the value of t_sale_chance.chance_source
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getChanceSource() {
        return chanceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.chance_source
     *
     * @param chanceSource the value for t_sale_chance.chance_source
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setChanceSource(String chanceSource) {
        this.chanceSource = chanceSource == null ? null : chanceSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.customer_name
     *
     * @return the value of t_sale_chance.customer_name
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.customer_name
     *
     * @param customerName the value for t_sale_chance.customer_name
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.cgjl
     *
     * @return the value of t_sale_chance.cgjl
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Integer getCgjl() {
        return cgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.cgjl
     *
     * @param cgjl the value for t_sale_chance.cgjl
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setCgjl(Integer cgjl) {
        this.cgjl = cgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.overview
     *
     * @return the value of t_sale_chance.overview
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.overview
     *
     * @param overview the value for t_sale_chance.overview
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.link_man
     *
     * @return the value of t_sale_chance.link_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.link_man
     *
     * @param linkMan the value for t_sale_chance.link_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.link_phone
     *
     * @return the value of t_sale_chance.link_phone
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.link_phone
     *
     * @param linkPhone the value for t_sale_chance.link_phone
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.description
     *
     * @return the value of t_sale_chance.description
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.description
     *
     * @param description the value for t_sale_chance.description
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.create_man
     *
     * @return the value of t_sale_chance.create_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.create_man
     *
     * @param createMan the value for t_sale_chance.create_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.assign_man
     *
     * @return the value of t_sale_chance.assign_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public String getAssignMan() {
        return assignMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.assign_man
     *
     * @param assignMan the value for t_sale_chance.assign_man
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setAssignMan(String assignMan) {
        this.assignMan = assignMan == null ? null : assignMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.assign_time
     *
     * @return the value of t_sale_chance.assign_time
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.assign_time
     *
     * @param assignTime the value for t_sale_chance.assign_time
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.state
     *
     * @return the value of t_sale_chance.state
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.state
     *
     * @param state the value for t_sale_chance.state
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.dev_result
     *
     * @return the value of t_sale_chance.dev_result
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Integer getDevResult() {
        return devResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.dev_result
     *
     * @param devResult the value for t_sale_chance.dev_result
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setDevResult(Integer devResult) {
        this.devResult = devResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.is_valid
     *
     * @return the value of t_sale_chance.is_valid
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.is_valid
     *
     * @param isValid the value for t_sale_chance.is_valid
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.create_date
     *
     * @return the value of t_sale_chance.create_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.create_date
     *
     * @param createDate the value for t_sale_chance.create_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_chance.update_date
     *
     * @return the value of t_sale_chance.update_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_chance.update_date
     *
     * @param updateDate the value for t_sale_chance.update_date
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_chance
     *
     * @mbg.generated Sun Aug 25 10:50:20 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", chanceSource=").append(chanceSource);
        sb.append(", customerName=").append(customerName);
        sb.append(", cgjl=").append(cgjl);
        sb.append(", overview=").append(overview);
        sb.append(", linkMan=").append(linkMan);
        sb.append(", linkPhone=").append(linkPhone);
        sb.append(", description=").append(description);
        sb.append(", createMan=").append(createMan);
        sb.append(", assignMan=").append(assignMan);
        sb.append(", assignTime=").append(assignTime);
        sb.append(", state=").append(state);
        sb.append(", devResult=").append(devResult);
        sb.append(", isValid=").append(isValid);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}